name: Split Test

on:
    push:
        branches:
            - main
        tags:
            - '*'

env:
    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
    packages_split:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                package:
                    -
                        local_path: 'Package01'
                        split_repository: 'test-split-package-01'
                    -
                        local_path: 'Package02'
                        split_repository: 'test-split-package-02'

        steps:
            -   uses: actions/checkout@v3

            -
                if: startsWith(github.ref, 'refs/tags/')
                uses: "symplify/monorepo-split-github-action@v2.3.0"
                with:
                    tag: ${GITHUB_REF#refs/tags/}

                    package_directory: 'src/${{ matrix.package.local_path }}'

                    repository_organization: 'SonyPradana'
                    repository_name: '${{ matrix.package.split_repository }}'

                    user_name: "SonyPradana"
                    user_email: "sonypradana@gmail.com"